config/routes.rb
Rails.application.routes.draw do
  get 'group_users/create'
  get 'group_users/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root "homes#top"
  get "home/about"=>"homes#about", as: "about"
  get "search" => "searches#search"
  get "chat/:id" => "chats#show", as: "chat"

  resources :groups do
    resource :group_users, only: [:create,:destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end
  resources :chats, only: [:create]
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
   resources :book_comments, only: [:create,:destroy]
   resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]do
    resource :relationships, only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "daily_posts" => "users#daily_posts"

  end
   get "search_book" => "books#search_book"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user
  has_many :view_counts, dependent: :destroy
  has_many :tags, through: :book_tags
  has_many :book_tags, dependent: :destroy

  validates :title,presence:true
  validates :body,presence:true,length:{maximum:200}

  scope :created_today, -> { where(created_at: Time.zone.now.all_day) }
  scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) }
  scope :created_week, -> { where(created_at: Time.zone.now.all_week) }
  scope :created_last_week, -> { where(created_at: 1.week.ago.all_week)}
  scope :created_2days, -> { where(created_at: 2.day.ago.all_day)}
  scope :created_3days, -> { where(created_at: 3.day.ago.all_day)}
  scope :created_4days, -> { where(created_at: 4.day.ago.all_day)}
  scope :created_5days, -> { where(created_at: 5.day.ago.all_day)}
  scope :created_6days, -> { where(created_at: 6.day.ago.all_day)}

  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search_word)
    Book.where(['category LIKE?',"#{search_word}"])
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/book_tag.rb
class BookTag < ApplicationRecord
  belongs_to :book
  belongs_to :tag
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence:true, length:{maximum:140}
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
  has_many :favorited_users, through: :favorites

     def favorited_by?(user)
  	   favorites.where(user_id: user.id).exists?  end
end

app/models/group.rb
class Group < ApplicationRecord
  has_one_attached :image
  has_many :group_users, dependent: :destroy
  belongs_to :owner, class_name: "User"

  has_many :users, through: :group_users, source: :user

  validates :name, presence: true
  validates :introduction, presence: true

  def get_image
    (image.attached?) ? image : "no_image.jpg"
  end

  def is_owned_by?(user)
    owner.id == user.id
  end

  def includesUser?(user)
    group_users.exists?(user_id: user.id)
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :book_tags, dependent: :destroy, foreign_key: "tag_id"
  has_many :books, through: :book_tags
  
  scope :merge_books, -> (tags){ }
  
  def self.search_books_for(content,method)
    
    if method == "perfect"
      tags = Tag.where(name: content)
    elsif method == "forward"  
      tags = Tag.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      tags = Tag.where('name LIKE ?', '%' + content)
    else
      tags = Tag.where('name LIKE ?', '%' + content + '%')
    end
    
    return tags.inject(init = []) {|result, tag| result + tag.books}
    
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :favorited_books, through: :favorites, source: :book
  has_many :view_counts, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :group_users, dependent: :destroy
  

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/view_count.rb
class ViewCount < ApplicationRecord
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @book = Book.new
    @groups = Group.all
  end

  def show
    @book = Book.new
    @group = Group.find(params[:id])
    @groupowner = User.find(@group.owner_id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render "edit"
    end

  end

  private

  def group_params
    params.require(:group).permit(:name,:introduction,:image)
  end

  def ensure_correct_user
    @group = Group.find(params[:id])
    unless @group.owner_id == current_user.id
      redirect_to groups_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/_form.html.erb
<%= form_with model: group, local: true do |f| %>
 <div class="form-group">
   <%= f.label :グループ名 %>
   <%= f.text_field :name, class: "form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :紹介文 %>
   <%= f.text_area :introduction, class: "form-control" %>
 </div>
 <div class="form-group">
   <%= f.label :グループ画像 %>
   <%= f.file_field :image, class: "form-control-file", accept: "image/*" %>
 </div>
 <div class="form-group">
   <%= f.submit class: "btn btn-info" %>
 </div>
<% end %>

app/views/groups/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= image_tag group.get_image, size: '50x50' %></td>
        <td><%= link_to group.name, group, class: "group_#{group.id}" %></td>
        <td><%= group.introduction %></td>
        <td><%= group.group_users.count %></td>
        <% if group.is_owned_by?(current_user) %>
         <td><%= link_to "Edit", edit_group_path(group), class: "group_#{group.id} btn btn-success" %></td>
        <% end %>
      </tr>
     <% end %>
  </tbody>
</table>

app/views/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 max-auto">
    <h3>Editing Group</h3>
      <%= render "form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render "books/form", book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
       <%= render "index", groups: @groups,users: @user %>
     </div>
   </div>
  </div>

app/views/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>Create Group</h3>
      <%= render "form", group: @group %>
    </div>
  </div>
</div>

app/views/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= render "users/info", user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render "books/form",book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th>メンバー</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tr>
          <td><%= image_tag @group.get_image, size: '50x50' %></td>
          <td><%= @group.name %></td>
          <td><%= @group.introduction %></td>
          <td>
            <li style="list-style: none;">
            <div><%= @groupowner.name %></div>
            <% @group.users.each do |user| %>
             <div><%= user.name %></div></li>
            <% end %>
          </td>
          <td>
            <% if @group.is_owned_by?(current_user) %>
             <%= link_to "Edit", edit_group_path(@group),class: "btn btn-sm btn-success" %>
             <%= link_to "Notice an Event", new_group_event_notice_path(@group), class: "btn btn-sm btn-info" %>
            <% elsif @group.includesUser?(current_user) %>
             <%= link_to "Leave this group", group_group_users_path(@group), method: :delete, class: "btn btn-sm btn-danger" %>
            <% else %>
             <%= link_to "Join this group", group_group_users_path(@group),method: :post, class: "btn btn-sm btn-success" %>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>