config/routes.rb
Rails.application.routes.draw do
  get 'group_users/create'
  get 'group_users/destroy'
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root "homes#top"
  get "home/about"=>"homes#about", as: "about"
  get "search" => "searches#search"
  get "chat/:id" => "chats#show", as: "chat"

  resources :groups do
    resource :group_users, only: [:create,:destroy]
    resources :event_notices, only: [:new, :create]
    get "event_notices" => "event_notices#sent"
  end
  resources :chats, only: [:create]
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update]do
   resources :book_comments, only: [:create,:destroy]
   resource :favorites, only: [:create, :destroy]
  end
  resources :users, only: [:index,:show,:edit,:update]do
    resource :relationships, only: [:create,:destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get "daily_posts" => "users#daily_posts"

  end
   get "search_book" => "books#search_book"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :favorited_books, through: :favorites, source: :book
  has_many :view_counts, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :group_users, dependent: :destroy
  

  validates :name, length: { minimum: 2, maximum: 20 }, uniqueness: true
  validates :introduction, length: { maximum: 50 }

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpg'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:update]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @week_book = @books.created_week
    @last_week_book = @books.created_last_week
  end

  def daily_posts
    user = User.find(params[:user_id])
    @books= user.books.where(created_at: params[:created_at].to_date.all_day)
    render :daily_posts_form
  end

  def index
    @user =current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render :edit
    else
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path, notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_daily_posts_form.html.erb
<%= form_with url: user_daily_posts_path(user), method: :get, local: false do |f| %>
 <%= f.date_field :created_at %>
 <%= f.submit "検索" , class: "btn btn-primary" %>
<% end %>

<div class= "daily_posts_table">
</div>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= image_tag user.get_profile_image, size: '50x50' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% if current_user.following?(user) %>
           <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
          <% else %>
           <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user, class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= image_tag user.get_profile_image, size:'100x100' %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
    <th>follows</th>
    <th><%= link_to user.followings.count,user_followings_path(user) %></th>
  </tr>
  <tr>
    <th>followers</th>
    <th><%= link_to user.followers.count,user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block edit_user_#{user.id}" do %>
    <i class="fas fa-user-cog"></i>
  <% end %>
</div>


  <% if current_user != user && current_user.following?(user) && user.following?(current_user) %>
   <%= link_to "chatを始める", chat_path(user.id), class: "ml-3" %>
  <% end %>

app/views/users/daily_posts_form.js.erb
$('.daily_posts_table').html(`
 <h2>検索結果</h2>
 <div class="card">
   <div class="card-header">投稿数</div>
   <div class="card-body">
     <%= j( @books.count ) %>
   </div>
 </div>
 `)

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model: @user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
        <h2>User info</h2>
        <%= render 'info', user: current_user %>
        <h2 class="mt-3">New book</h2>
        <%= render 'books/form', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <div><%= link_to "グループを作成する", new_group_path %> | <%= link_to "グループ一覧", groups_path %></div>
      <%= render 'index',users: @users %>
    </div>
 </div>
</div>

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <% if current_user.following?(@user) %>
       <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-primary" %>
      <% else %>
       <%= link_to "フォローする", user_relationships_path(@user.id), method: :post,class: "btn btn-primary" %>
      <% end %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books,user: @user %>
    <div class = "table_width">
      <table class="table table-bordered">
        <%= render 'daily_posts_form', user: @user %>
        <h2>投稿数の前日比・先週比</h2>
        <thead>
          <tr>
            <th>今日の投稿数</th>
            <th>前日の投稿数</th>
            <th>前日比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @today_book.count %></td>
            <td><%= @yesterday_book.count %></td>
            <td>
              <% if @yesterday_book.count == 0 %>
              前日の投稿はありません
              <% else %>
               <% @the_day_before = @today_book.count / @yesterday_book.count.to_f %>
               <%= (@the_day_before * 100).round %>
              <% end %>
            </td>
          </tr>
        </tbody>
        <thead>
          <tr>
            <th>今週の投稿数</th>
            <th>先週の投稿数</th>
            <th>先週比</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @week_book.count %></td>
            <td><%= @last_week_book.count %></td>
            <td>
              <% if @last_week_book.count == 0 %>
              先週の投稿はありません
              <% else %>
               <% @the_week_before = @week_book.count / @last_week_book.count.to_f %>
               <%= (@the_week_before * 100).round %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <h2>７日分の投稿数</h2>
      <table class="table">
        <thead>
          <tr>
            <th>６日前</th>
            <th>５日前</th>
            <th>４日前</th>
            <th>３日前</th>
            <th>２日前</th>
            <th>１日前</th>
            <th>今日</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th><%= @books.created_6days.count %></th>
            <th><%= @books.created_5days.count %></th>
            <th><%= @books.created_4days.count %></th>
            <th><%= @books.created_3days.count %></th>
            <th><%= @books.created_2days.count %></th>
            <th><%= @yesterday_book.count %></th>
            <th><%= @today_book.count %></th>
          </tr>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</div>
<canvas id="myChart"></canvas>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.bundle.js"></script>
  <script>
    var ctx = document.getElementById('myChart');
    var chart = new Chart(ctx, {
        // 作成したいチャートのタイプ
        type: 'line',
        // データセットのデータ
        data: {
            labels: ["6日前", "5日前", "4日前", "3日前", "2日前", "1日前", "今日"],
            datasets: [{
                label: "投稿した本の数",
                data: [
                    <%= @books.created_6days.count %>,
                    <%= @books.created_5days.count %>,
                    <%= @books.created_4days.count %>,
                    <%= @books.created_3days.count %>,
                    <%= @books.created_2days.count %>,
                    <%= @yesterday_book.count %>,
                    <%= @today_book.count %>
                ],
                backgroundColor: 'rgba(0,0,0,0)',
                borderColor: 'rgba(0,0,255,1)',
            }]
        },

        // 設定オプション
        options: {
          title: {
            display: true,
            text: '7日間の投稿数の比較'
          },
          responsive: true,
        }
    });
  </script>